import { GameName, SupportedLang, ThcrapProfileData } from './data-types';

export const thcrapGameNames: {[gameName in GameName] : string} = {
    hrtp: 'th01',
    soew: 'th02',
    podd: 'th03',
    lls: 'th04',
    ms: 'th05',
    eosd: 'th06',
    pcb: 'th07',
    in: 'th08',
    pofv: 'th09',
    mof: 'th10',
    sa: 'th11',
    ufo: 'th12',
    td: 'th13',
    ddc: 'th14',
    lolk: 'th15',
    hsifs: 'th16',
    wbawc: 'th17',
    um: 'th18',
    iamp: 'th75',
    swr: 'th105',
    soku: 'th123',
    hm: 'th135',
    ulil: 'th145',
    aocf: 'th155',
    stb: 'th95',
    ds: 'th125',
    gfw: 'th128',
    isc: 'th143',
    vd: 'th165'
} as const;
export const gameTitles: Record<SupportedLang, {[gameName in GameName] : string}> = {
    en: {
        hrtp: 'Highly Responsive to Prayers',
        soew: 'Story of Eastern Wonderland',
        podd: 'Phantasmagoria of Dim. Dream',
        lls: 'Lotus Land Story',
        ms: 'Mystic Square',
        eosd: 'Embodiment of Scarlet Devil',
        pcb: 'Perfect Cherry Blossom',
        in: 'Imperishable Night',
        pofv: 'Phantasmagoria of Flower View',
        mof: 'Mountain of Faith',
        sa: 'Subterranean Animism',
        ufo: 'Undefined Fantastic Object',
        td: 'Ten Desires',
        ddc: 'Double Dealing Character',
        lolk: 'Legacy of Lunatic Kingdom',
        hsifs: 'Hidden Star in Four Seasons',
        wbawc: 'Wily Beast and Weakest Creature',
        um: 'Unconnected Marketeers',
        iamp: 'Immaterial and Missing Power',
        swr: 'Scarlet Weather Rhapsody',
        soku: 'Hisotensoku',
        hm: 'Hopeless Masquerade',
        ulil: 'Urban Legend in Limbo',
        aocf: 'Antinomy of Common Flowers',
        stb: 'Shoot the Bullet',
        ds: 'Double Spoiler',
        gfw: 'Great Fairy Wars',
        isc: 'Impossible Spell Card',
        vd: 'Violet Detector'
    },
    ru: {
        hrtp: 'Highly Responsive to Prayers',
        soew: 'Story of Eastern Wonderland',
        podd: 'Phantasmagoria of Dim. Dream',
        lls: 'Lotus Land Story',
        ms: 'Mystic Square',
        eosd: 'Embodiment of Scarlet Devil',
        pcb: 'Perfect Cherry Blossom',
        in: 'Imperishable Night',
        pofv: 'Phantasmagoria of Flower View',
        mof: 'Mountain of Faith',
        sa: 'Subterranean Animism',
        ufo: 'Undefined Fantastic Object',
        td: 'Ten Desires',
        ddc: 'Double Dealing Character',
        lolk: 'Legacy of Lunatic Kingdom',
        hsifs: 'Hidden Star in Four Seasons',
        wbawc: 'Wily Beast and Weakest Creature',
        um: 'Unconnected Marketeers',
        iamp: 'Immaterial and Missing Power',
        swr: 'Scarlet Weather Rhapsody',
        soku: 'Hisotensoku',
        hm: 'Hopeless Masquerade',
        ulil: 'Urban Legend in Limbo',
        aocf: 'Antinomy of Common Flowers',
        stb: 'Shoot the Bullet',
        ds: 'Double Spoiler',
        gfw: 'Great Fairy Wars',
        isc: 'Impossible Spell Card',
        vd: 'Violet Detector'
    },
    jp: {
        hrtp: '東方靈異伝　～ Highly Responsive to Prayers',
        soew: '東方封魔録　～ Story of Eastern Wonderland',
        podd: '東方夢時空　～ Phantasmagoria of Dim.Dream',
        lls: '東方幻想郷　～ Lotus Land Story',
        ms: '東方怪綺談　～ Mystic Square',
        eosd: '東方紅魔郷　～ the Embodiment of Scarlet Devil',
        pcb: '東方妖々夢　～ Perfect Cherry Blossom',
        in: '東方永夜抄　～ Imperishable Night',
        pofv: '東方花映塚　～ Phantasmagoria of Flower View',
        mof: '東方風神録　～ Mountain of Faith',
        sa: '東方地霊殿　～ Subterranean Animism',
        ufo: '東方星蓮船　～ Undefined Fantastic Object',
        td: '東方神霊廟　～ Ten Desires',
        ddc: '東方輝針城　～ Double Dealing Character',
        lolk: '東方紺珠伝　～ Legacy of Lunatic Kingdom',
        hsifs: '東方天空璋　～ Hidden Star in Four Seasons',
        wbawc: '東方鬼形獣　～ Wily Beast and Weakest Creature',
        um: '東方虹龍洞　～ Unconnected Marketeers',
        iamp: '東方萃夢想　～ Immaterial and Missing Power',
        swr: '東方緋想天　～ Scarlet Weather Rhapsody',
        soku: '東方非想天則　～ 超弩級ギニョルの謎を追え',
        hm: '東方心綺楼　～ Hopeless Masquerade',
        ulil: '東方深秘録　～ Urban Legend in Limbo',
        aocf: '東方憑依華　～ Antinomy of Common Flowers',
        stb: '東方文花帖　～ Shoot the Bullet',
        ds: 'ダブルスポイラー　～ 東方文花帖',
        gfw: '妖精大戦争　～ 東方三月精',
        isc: '弾幕アマノジャク　～ Impossible Spell Card',
        vd: '秘封ナイトメアダイアリー　〜 Violet Detector'
    }
};
export const shortGameTitles: Record<SupportedLang, {[gameName in GameName] : string}> = {
    en: {
        hrtp: 'HRtP',
        soew: 'SoEW',
        podd: 'PoDD',
        lls: 'LLS',
        ms: 'MS',
        eosd: 'EoSD',
        pcb: 'PCB',
        in: 'IN',
        pofv: 'PoFV',
        mof: 'MoF',
        sa: 'SA',
        ufo: 'UFO',
        td: 'TD',
        ddc: 'DDC',
        lolk: 'LoLK',
        hsifs: 'HSiFS',
        wbawc: 'WBaWC',
        um: 'UM',
        iamp: 'IaMP',
        swr: 'SWR',
        soku: 'Hisotensoku',
        hm: 'HM',
        ulil: 'ULiL',
        aocf: 'AoCF',
        stb: 'StB',
        ds: 'DS',
        gfw: 'GFW',
        isc: 'ISC',
        vd: 'VD'
    },
    ru: {
        hrtp: 'HRtP',
        soew: 'SoEW',
        podd: 'PoDD',
        lls: 'LLS',
        ms: 'MS',
        eosd: 'EoSD',
        pcb: 'PCB',
        in: 'IN',
        pofv: 'PoFV',
        mof: 'MoF',
        sa: 'SA',
        ufo: 'UFO',
        td: 'TD',
        ddc: 'DDC',
        lolk: 'LoLK',
        hsifs: 'HSiFS',
        wbawc: 'WBaWC',
        um: 'UM',
        iamp: 'IaMP',
        swr: 'SWR',
        soku: 'Hisotensoku',
        hm: 'HM',
        ulil: 'ULiL',
        aocf: 'AoCF',
        stb: 'StB',
        ds: 'DS',
        gfw: 'GFW',
        isc: 'ISC',
        vd: 'VD'
    },
    jp: {
        hrtp: '東方靈異伝',
        soew: '東方封魔録',
        podd: '東方夢時空',
        lls: '東方幻想郷',
        ms: '東方怪綺談',
        eosd: '東方紅魔郷',
        pcb: '東方妖々夢',
        in: '東方永夜抄',
        pofv: '東方花映塚',
        mof: '東方風神録',
        sa: '東方地霊殿',
        ufo: '東方星蓮船',
        td: '東方神霊廟',
        ddc: '東方輝針城',
        lolk: '東方紺珠伝',
        hsifs: '東方天空璋',
        wbawc: '東方鬼形獣',
        um: '東方虹龍洞',
        iamp: '東方萃夢想',
        swr: '東方緋想天',
        soku: '東方非想天則',
        hm: '東方心綺楼',
        ulil: '東方深秘録',
        aocf: '東方憑依華',
        stb: '東方文花帖',
        ds: 'ダブルスポイラー',
        gfw: '妖精大戦争',
        isc: '弾幕アマノジャク',
        vd: '秘封ナイトメアダイアリー'
    }
};
export const defaultThcrapProfileData: ThcrapProfileData = {
    console: false,
    dat_dump: false,
    patches: []
};
export const categories: Record<'mainGames' | 'fightingGames' | 'otherGames', GameName[]> = {
    mainGames: ['hrtp', 'soew', 'podd', 'lls', 'ms', 'eosd', 'pcb', 'in', 'pofv', 'mof', 'sa', 'ufo', 'td', 'ddc', 'lolk', 'hsifs', 'wbawc', 'um'],
    fightingGames: ['iamp', 'swr', 'soku', 'hm', 'ulil', 'aocf'],
    otherGames: ['stb', 'ds', 'gfw', 'isc', 'vd']
};
export const categoryTitles: Record<keyof typeof categories, Record<SupportedLang, string>> = {
    mainGames: {
        en: 'Main Games',
        ru: 'Основные игры',
        jp: 'メインゲーム'
    },
    fightingGames: {
        en: 'Fighting Games',
        ru: 'Файтинги',
        jp: '格闘ゲーム'
    },
    otherGames: {
        en: 'Other Games',
        ru: 'Другие игры',
        jp: '他のゲーム'
    }
};
